---
name: Build and Push Docker Images for Renovate PR

on:
  merge_group:
  pull_request:
    branches:
      - main
    paths:
      - 'python/**'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  docker-build-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          cd python
          ALPINE_VERSION=$(grep -oP '^ARG ALPINE_VERSION=\K.*' Dockerfile)
          echo "ALPINE_VERSION=${ALPINE_VERSION}" >> $GITHUB_ENV
          echo "ALPINE_VERSION=${ALPINE_VERSION}"
          PYTHON_VERSION=$(grep -oP "^ARG PYTHON_VERSION=\K.*" Dockerfile)
          echo "PYTHON_VERSION=${PYTHON_VERSION}" >> $GITHUB_ENV
          echo "PYTHON_VERSION=${PYTHON_VERSION}"

      - name: Build and push (Dry run)
        uses: docker/build-push-action@v6
        with:
          context: python
          file: python/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          tags: |
            ghcr.io/${{ github.repository }}/python:alpine${{ env.ALPINE_VERSION }}
            ghcr.io/${{ github.repository }}/python:latest
