---
name: Build and Push Docker Images for Java

on:
  push:
    branches:
      - main
    paths:
      - 'java/**'
  workflow_dispatch:

jobs:
  docker-build-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_SECRET }}

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          cd java
          ALPINE_VERSION=$(grep -oP '^ARG ALPINE_VERSION=\K.*' Dockerfile)
          echo "ALPINE_VERSION=${ALPINE_VERSION}" >> $GITHUB_ENV
          echo "ALPINE_VERSION=${ALPINE_VERSION}"
          OPENJDK_VERSION=$(grep -oP "^ARG OPENJDK_VERSION=\K.*" Dockerfile)
          echo "OPENJDK_VERSION=${OPENJDK_VERSION}" >> $GITHUB_ENV
          echo "OPENJDK_VERSION=${OPENJDK_VERSION}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: java
          file: java/Dockerfile
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/java:alpine${{ env.ALPINE_VERSION }}
            ghcr.io/${{ github.repository }}/java:latest
