---
name: Build and Push Docker Images for Renovate PR

on:
  merge_group:
  pull_request:
    branches:
      - main
    paths:
      - 'go/**'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  docker-build-go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          cd go
          ALPINE_VERSION=$(grep -oP '^ARG ALPINE_VERSION=\K.*' Dockerfile)
          echo "ALPINE_VERSION=${ALPINE_VERSION}" >> $GITHUB_ENV
          echo "ALPINE_VERSION=${ALPINE_VERSION}"
          GO_VERSION=$(grep -oP "^ARG GO_VERSION=\K.*" Dockerfile)
          echo "GO_VERSION=${GO_VERSION}" >> $GITHUB_ENV
          echo "GO_VERSION=${GO_VERSION}"

      - name: Build and push (Dry run)
        uses: docker/build-push-action@v6
        with:
          context: go
          file: go/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          tags: |
            ghcr.io/${{ github.repository }}/go:alpine${{ env.ALPINE_VERSION }}
            ghcr.io/${{ github.repository }}/go:latest

      - name: Run Slack Notification
        if: always()
        uses: opslabhqx/action-slacknotify@v1
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
